# A unique identifier for the head node and workers of this cluster.
cluster_name: minimal

# Cloud-provider specific configuration.
provider:
  type: gcp
  region: us-central1
  availability_zone: us-central1-a
  project_id: xxxxxxx
  #cache_stopped_nodes: bool
